// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"github.com/google/uuid"
)

type LuckpermsGroup struct {
	Name string
}

type LuckpermsUserPermission struct {
	ID         int32
	Uuid       uuid.UUID
	Permission string
	Value      int32
	Server     string
	World      string
	Expiry     int32
	Contexts   string
}
