// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: queries.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getPermission = `-- name: GetPermission :one
SELECT id, uuid, permission, value, server, world, expiry, contexts FROM luckperms_user_permissions
WHERE uuid = $1 AND (permission = $2 OR permission = '*')
LIMIT 1
`

type GetPermissionParams struct {
	Uuid       uuid.UUID
	Permission string
}

func (q *Queries) GetPermission(ctx context.Context, arg GetPermissionParams) (LuckpermsUserPermission, error) {
	row := q.db.QueryRowContext(ctx, getPermission, arg.Uuid, arg.Permission)
	var i LuckpermsUserPermission
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Permission,
		&i.Value,
		&i.Server,
		&i.World,
		&i.Expiry,
		&i.Contexts,
	)
	return i, err
}
